spring.application.name=PassportInternship
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sam
spring.datasource.password=sam
spring.batch.initialize-schema=always
spring.batch.job.enabled=true